on:
  release:
    types: [created]

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24 # npm 11.5.1 or later is required for OIDC
          registry-url: https://registry.npmjs.org

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Publish
        run: npm publish
